// <auto-generated />
using System;
using MassTransit.EntityFrameworkCoreIntegration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobService.Service.Migrations
{
    [DbContext(typeof(JobServiceSagaDbContext))]
    partial class JobServiceSagaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.JobAttemptSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstanceAddress")
                        .HasColumnType("text");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("StatusCheckTokenId")
                        .HasColumnType("uuid");

                    b.HasKey("CorrelationId");

                    b.HasIndex("JobId", "RetryAttempt")
                        .IsUnique();

                    b.ToTable("JobAttemptSaga");
                });

            modelBuilder.Entity("MassTransit.JobSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Completed")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("Faulted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Job")
                        .HasColumnType("text");

                    b.Property<Guid?>("JobRetryDelayToken")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("JobSlotWaitToken")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("JobTimeout")
                        .HasColumnType("interval");

                    b.Property<Guid>("JobTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceAddress")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Started")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Submitted")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CorrelationId");

                    b.ToTable("JobSaga");
                });

            modelBuilder.Entity("MassTransit.JobTypeSaga", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<int>("ActiveJobCount")
                        .HasColumnType("integer");

                    b.Property<string>("ActiveJobs")
                        .HasColumnType("text");

                    b.Property<int>("ConcurrentJobLimit")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentState")
                        .HasColumnType("integer");

                    b.Property<string>("Instances")
                        .HasColumnType("text");

                    b.Property<int?>("OverrideJobLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OverrideLimitExpiration")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("CorrelationId");

                    b.ToTable("JobTypeSaga");
                });
#pragma warning restore 612, 618
        }
    }
}
